// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class WiZkiD_Lootable_FireWood_Piles
    {
        public static class Container
        {
            private static FormLink<IContainerGetter> Construct(uint id) => new(ModKey.MakeFormKey(id));
            public static FormLink<IContainerGetter> wiz_FireWoodpileSmall => Construct(0x3209f2);
            public static FormLink<IContainerGetter> wiz_FireWoodpileLarge => Construct(0x3209f3);
            public static FormLink<IContainerGetter> wiz_FireWoodPileHuge => Construct(0x3534af);
            public static FormLink<IContainerGetter> wiz_FireWoodPileHuge_LightSN => Construct(0x3534b1);
            public static FormLink<IContainerGetter> wiz_FireWoodpileSmall_SparseSN => Construct(0x3534b2);
            public static FormLink<IContainerGetter> wiz_FireWoodpileLarge_SparseSN => Construct(0x3534b3);
            public static FormLink<IContainerGetter> wiz_FireWoodpileMedium_LightSN => Construct(0x3534b4);
            public static FormLink<IContainerGetter> wiz_FireWoodpileLarge_LightSN => Construct(0x3534b6);
            public static FormLink<IContainerGetter> wiz_FireWoodpileSmall_LightSN => Construct(0x3534b7);
            public static FormLink<IContainerGetter> wiz_FireWoodpileMedium => Construct(0x3534b8);
        }
    }
}
