// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class WiZkiD_Lootable_FireWood_Piles
    {
        public static class Container
        {
            private static FormLink<IContainerGetter> Construct(uint id) => new(ModKey.MakeFormKey(id));
            public static FormLink<IContainerGetter> wiz_FireWoodpileSmall01 => Construct(0x3209f2);
            public static FormLink<IContainerGetter> wiz_FireWoodpileLarge01 => Construct(0x3209f3);
            public static FormLink<IContainerGetter> wiz_FireWoodPileHuge1 => Construct(0x3534af);
            public static FormLink<IContainerGetter> wiz_FireWoodPileHuge1_LightSN => Construct(0x3534b1);
            public static FormLink<IContainerGetter> wiz_FireWoodpileSmall01_SparseSN => Construct(0x3534b2);
            public static FormLink<IContainerGetter> wiz_FireWoodpileLarge01_SparseSN => Construct(0x3534b3);
            public static FormLink<IContainerGetter> wiz_FireWoodpileMedium01_LightSN => Construct(0x3534b4);
            public static FormLink<IContainerGetter> wiz_FireWoodpileLarge01_LightSN => Construct(0x3534b6);
            public static FormLink<IContainerGetter> wiz_FireWoodpileSmall01_LightSN => Construct(0x3534b7);
            public static FormLink<IContainerGetter> wiz_FireWoodpileMedium01 => Construct(0x3534b8);
        }
    }
}
