// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class WiZkiD_Lootable_FireWood_Piles
    {
        public static class Container
        {
            private static FormLink<IContainerGetter> Construct(uint id) => new(ModKey.MakeFormKey(id));
            public static FormLink<IContainerGetter> wiz_FireWoodpileSmall01 => Construct(0x800);
            public static FormLink<IContainerGetter> wiz_FireWoodpileLarge01 => Construct(0x801);
            public static FormLink<IContainerGetter> wiz_FireWoodPileHuge1 => Construct(0x804);
            public static FormLink<IContainerGetter> wiz_FireWoodPileHuge1_LightSN => Construct(0x806);
            public static FormLink<IContainerGetter> wiz_FireWoodpileSmall01_SparseSN => Construct(0x807);
            public static FormLink<IContainerGetter> wiz_FireWoodpileLarge01_SparseSN => Construct(0x808);
            public static FormLink<IContainerGetter> wiz_FireWoodpileMedium01_LightSN => Construct(0x809);
            public static FormLink<IContainerGetter> wiz_FireWoodpileLarge01_LightSN => Construct(0x80b);
            public static FormLink<IContainerGetter> wiz_FireWoodpileSmall01_LightSN => Construct(0x80c);
            public static FormLink<IContainerGetter> wiz_FireWoodpileMedium01 => Construct(0x80d);
        }
    }
}
